// SPDX-License-Identifier: GPL-3.0-or-later
/*
 * Copyright (C) 2019 CAMELab
 *
 * Author: Donghyun Gouk <kukdh1@camelab.org>
 */

#pragma once

#ifndef __CPU_DEF__
#define __CPU_DEF__

#include <cinttypes>

namespace SimpleSSD::CPU {

enum class Namespace : uint16_t {
  FTL,
  FTL__PAGE_MAPPING,
  ICL,
  ICL__GENERIC_CACHE,
  HIL,
  NVME__CONTROLLER,
  NVME__PRPLIST,
  NVME__SGL,
  NVME__SUBSYSTEM,
  NVME__NAMESPACE,
  NVME__OCSSD,
  UFS__DEVICE,
  SATA__DEVICE,
};

enum class Function : uint16_t {
  // Common
  READ,
  WRITE,
  FLUSH,
  TRIM,
  FORMAT,

  // FTL__PAGE_MAPPING
  READ_INTERNAL,
  WRITE_INTERNAL,
  ERASE_INTERNAL,
  TRIM_INTERNAL,
  SELECT_VICTIM_BLOCK,
  DO_GARBAGE_COLLECTION,

  // NVME__CONTROLLER / NVME__SUBSYSTEM
  CREATE_CQ,
  CREATE_SQ,

  // NVME__CONTROLLER
  COLLECT_SQ,
  HANDLE_REQUEST,
  WORK,
  COMPLETION,

  // NVME__PRPLIST
  GET_PRPLIST_FROM_PRP,

  // NVME__SGL
  PARSE_SGL_SEGMENT,

  // NVME__SUBSYSTEM / NVME__NAMESPACE
  SUBMIT_COMMAND,

  // NVME__SUBSYSTEM
  CONVERT_UNIT,
  FORMAT_NVM,

  // NVME__NAMESPACE
  DATASET_MANAGEMENT,

  // NVME__OCSSD
  VECTOR_CHUNK_READ,
  VECTOR_CHUNK_WRITE,
  VECTOR_CHUNK_RESET,
  PHYSICAL_PAGE_READ,
  PHYSICAL_PAGE_WRITE,
  PHYSICAL_BLOCK_ERASE,

  // UFS__DEVICE
  PROCESS_QUERY_COMMAND,
  PROCESS_COMMAND,
  PRDT_READ,
  PRDT_WRITE,

  // SATA__DEVICE
  READ_DMA,
  READ_NCQ,
  READ_DMA_SETUP,
  READ_DMA_DONE,
  WRITE_DMA,
  WRITE_NCQ,
  WRITE_DMA_SETUP,
  WRITE_DMA_DONE,
};

}  // namespace SimpleSSD::CPU

#endif
